# Generated by Django 5.0.6 on 2024-07-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_booking_check_in_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in_date',
            field=models.DateField(verbose_name='Дата заезда'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out_date',
            field=models.DateField(verbose_name='Дата выезда'),
        ),
    ]
