# Generated by Django 5.0.6 on 2024-07-02 12:35

from django.db import migrations, models

import rooms.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_booking_check_in_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in_date',
            field=models.DateField(validators=[rooms.validators.validate_check_in_date_is_not_past], verbose_name='Дата заезда'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out_date',
            field=models.DateField(validators=[rooms.validators.validate_check_out_date_is_later_than_check_in_date], verbose_name='Дата выезда'),
        ),
    ]
