# Generated by Django 5.0.6 on 2024-07-03 06:07

import rooms.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_alter_booking_check_out_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in_date',
            field=models.DateTimeField(validators=[rooms.validators.validate_check_in_date_is_not_past], verbose_name='Дата заезда'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out_date',
            field=models.DateTimeField(verbose_name='Дата выезда'),
        ),
    ]
