# Generated by Django 5.0.6 on 2024-07-03 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_alter_booking_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1, message='Номер должен быть больше 0')], verbose_name='Номер комнаты'),
        ),
    ]
